### ISSUE TITLE
Q: Is there asyncStorage.open()

### ISSUE THREAD

**Issue by noiv** [WebReflection/db#1]
Hi,

i have the lib in use in development and it works good. However, one thing makes me wondering, maybe I missed an essential part of the docs. On each (re-)load 'asyncStorage.create(dbName, function(mydb){...' is executed and leads to multiple entries of dbName in Chrome/Resources/Database. Currently I keep overall size of values stored low, so it will fit in a cookie as last resort. 

But wouldn't these multiple entries effect maximum storage size?

**Comment by WebReflection** [comment]
the Chrome is using the WebSQL database and the fact you have multiple db
in your debugger does not mean it creates multiple databases :-)

Data is persistent indeed and the API used behind the scene is
openDatabase, not createDatabase.

The db.create() name might mislead but you can consider it the equivalent
of db.open() where if the db is not there, it's created.

Maybe I'll simply alias .create() with .open()

Anyway, if you close the debugger and reopen again you'll see only one
instance of the database ;-)

hope this helps

On Tue, Jul 3, 2012 at 12:08 PM, noiv <
reply@reply.github.com

**Comment by noiv** [comment]
Thanks, for the explanation, was just a semantic issue :) . No need to change working code.

**Comment by jfktrey** [comment]
I was confused about this, too. The documentation doesn't really make this clear and the fact that multiple databases show up in Chrome adds to the confusion. A quick clarification in the readme would be great.

**Comment by WebReflection** [comment]
a clarification in Chrome developers tool ? sure it would be appreciated … since it has nothing to do with db, right?

**Comment by jfktrey** [comment]
Right, I meant to say the fact that create() also opens databases.

**Comment by WebReflection** [comment]
so you are suggesting that aliasing it would make more sense? `db.open()` as alias of `db.create()` … might do that :-)
