### ISSUE TITLE
iOS Chrome fails with SECURITY_ERR: DOM Exception 18

### ISSUE THREAD

**Issue by trodrigues** [WebReflection/db#2]
iOS Chrome reports itself as WebSQL capable (openDatabase in window returns true), but when trying to use it, it throws a SECURITY_ERR: DOM Exception 18.

I'm not sure if this is a restriction imposed on all iOS UIWebViews because some googling suggests developers who inject their own webviews on their apps can do some things to try and bypass this, but not having any knowledge in iOS development I'm not sure if it would be worth also filing a bug in iOS Chrome for this.

**Comment by WebReflection** [comment]
can you please double check this is still the case ? thanks!

**Comment by trodrigues** [comment]
Looks like it isn't. I created a simple test case at http://trodrigues.net/asynctest.html and on iOS chrome it does report itself as using WebSQL and it still works properly. They still support WebSQL so I just assume they fixed that UIWebView restriction somehow.
